site_name: 晶尘CryDust's Blog
repo_url: https://github.com/JcMarical/CryDustBlog #（请修改为你自己的仓库地址）
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  custom_dir: overrides # materal覆盖原主题存放的文件
  favicon: assets/favicon.ico

  # 字体
  font:
    text: "'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"
    code: "'JetBrains Mono', 'LXGW WenKai Screen', 'Noto Sans SC', 'Microsoft YaHei', sans-serif"

  #图标
  icon:
    repo: fontawesome/brands/github
    logo: octicons/stack-24
    edit: material/pencil
    tag:
      default: fontawesome/solid/hashtag

  #颜色主题
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/circle-slice-4
        name: Auto Mode
        accent: teal #强调色

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/circle-slice-8
        name: Light Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/circle-outline
        name: Dark Mode

  #启用的功能
  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    # - content.code.annotate
    - content.action.edit

    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs   #导航选项卡
    - navigation.top  #顶部显示导航
    - navigation.path #导航栏中显示当前也没路径
    # - navigation.indexes
    # - navigation.tracking
    # - navigation.footer
    # - navigation.sections

    # toc.follow
    - toc.integrate #大纲展示

    #搜索
    - search.suggest 
    - search.highlight
    - search.share


# Extensions

# Markdown扩展
markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  #- callouts
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      # auto_title: true
      # linenums: true
      # anchor_linenums: true
      # line_spans: __span # When this option is set, each line of a code block is wrapped in a span, which is essential for features like line highlighting to work correctly
      use_pygments: true

      # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#extended-pygments-lexer-options
      extend_pygments_lang:
        - name: antlr4
          lang: antlr
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      # https://python-markdown.github.io/extensions/toc/
      permalink: true
      separator: "-"
      # 生成可读的 unicode slug
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - roamlinks 
  - blog:
      enabled: true
      blog_toc: true
      post_dir: docs/
      post_date_format: yyyy-MM-dd
      post_url_format: "posts/{slug}"
      post_excerpt: required
      post_excerpt_max_authors: 0
      post_readtime: true
      post_readtime_words_per_minute: 180
      archive: true
      archive_date_format: yyyy 年 MM 月
      archive_url_date_format: yyyy/MM
      archive_toc: true
      categories: true
      categories_url_format: "categories/{slug}"
      categories_toc: true
      authors: false
      pagination: true
      pagination_per_page: 10
      pagination_format: "~2~"
      pagination_if_single_page: true
      pagination_keep_content: true
  - meta